appearance_thresh: 0.25
cmc_method: sparseOptFlow
frame_rate: 30
lambda_: 0.2
match_thresh: 0.65
new_track_thresh: 0.5
overlap_thresh: 0.55
proximity_thresh: 0.1
second_match_thresh: 0.19
track_buffer: 35
track_high_thresh: 0.5
track_low_thresh: 0.1
